apiVersion: v1
kind: Secret
metadata:
  name: banking-secret-tls
  namespace: default
data:
  tls.crt: MIIDUTCCAjmgAwIBAgIUDNYzAUx2E4QWwOLL427oe3dHSLgwDQYJKoZIhvcNAQEL
  BQAwODEVMBMGA1UEAwwMMTkyLjE2OC40OS4yMQswCQYDVQQGEwJERTESMBAGA1UE
  BwwJRnJhbmtmdXJ0MB4XDTIyMDUxMTExMTMyNFoXDTIzMDUxMTExMTMyNFowODEV
  MBMGA1UEAwwMMTkyLjE2OC40OS4yMQswCQYDVQQGEwJERTESMBAGA1UEBwwJRnJh
  bmtmdXJ0MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAwWx0HLwHjsbQ
  EIUrAIF1pG6H9ySjRNvT52wCKWEp4cTVWMiJBctZ835bjuRvEOd6lebDlj40g56u
  M2w/dMd8H+QZUeI5q8x+gv+eTB1jZ4guNcWsYXoIqWmETI1E90oX6ysOZF1t5yN/
  HPGzrKwwyTMFvgD9WuzR9bnMwa1SieFBAxBcWMcK4JlANqaPgor2U5R6atbQ5XL2
  VHHEDON9FP5WG5nD2X3pdC0yaNKvZWcrCcV6eNk/UqXYti56rmzQtlpn+bw9f4hd
  QHAyvXAcafEffm5vDDH4voenGOLDjlxgTHiEVUvAJN3Ixq9H+X1Aa/7kzhPxZ18w
  YEe6AgcT6wIDAQABo1MwUTAdBgNVHQ4EFgQUTLzSCRkEGvJnWn7C+oNRdLSh80Mw
  HwYDVR0jBBgwFoAUTLzSCRkEGvJnWn7C+oNRdLSh80MwDwYDVR0TAQH/BAUwAwEB
  /zANBgkqhkiG9w0BAQsFAAOCAQEApsyTMkO3bzsIfBp8qQDdHQ3ZKwb3/135ZGeB
  p045Hf6k/urX+Gs0DpE1F2Y///v+NJ5zym4BoXsLdqT1grOduO+3agMCOTtaNLKw
  dPLYJKmsMdEqSeINnkAUzniavxJlyyTUx1FZDhEKtR0wVz2Sp218ieIPm9BQt1Zy
  /VV7N1OTRlJP53TSui3pvBHE/lqe3emvbZLRRtJdfXkenob9AoitdSpV5EQUrnH2
  UO/LYmCqKr75UUS+DK3Yfh0rhCELpcmtxmEfX7Nb/a4aqx3iQS+7tRrbvAWYxw7t
  58kGMt+IdM9xhe02lNZlIb1XLRb1EuflZlb/9YgHGO7tsQd7hA==

  tls.key: MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDBbHQcvAeOxtAQ
  hSsAgXWkbof3JKNE29PnbAIpYSnhxNVYyIkFy1nzfluO5G8Q53qV5sOWPjSDnq4z
  bD90x3wf5BlR4jmrzH6C/55MHWNniC41xaxhegipaYRMjUT3ShfrKw5kXW3nI38c
  8bOsrDDJMwW+AP1a7NH1uczBrVKJ4UEDEFxYxwrgmUA2po+CivZTlHpq1tDlcvZU
  ccQM430U/lYbmcPZfel0LTJo0q9lZysJxXp42T9Spdi2LnqubNC2Wmf5vD1/iF1A
  cDK9cBxp8R9+bm8MMfi+h6cY4sOOXGBMeIRVS8Ak3cjGr0f5fUBr/uTOE/FnXzBg
  R7oCBxPrAgMBAAECggEBAJgZP4kk9tB4WD7VaQZBxw+hdzuJzPWl45E0ptKBPFzz
  2kyxjMZIrRhDQZ4w1YG2dPgRebXYfpUNn7CCK7gZ8epmBN8WBQGqkcVTWthBt9w/
  Aw93vOD+BHerqMRFxnirA/oCZpPXwEek6x0Il6Bt2wMsIxTRVGk+lrAjBfc64w/V
  96L0f8+1gzz0eYzEwDa+FpSFAA2YcXfi5Owapq/GDobuMde0YEngdANb4lMLgA83
  ENz6AdC22vPzwsgZXpaL3BFjU6/HiHZdZVbGG3lK/uJKU9u7mcmMlBmHVlulMMVV
  BgooFHU+cjFLNAeeeW4Q8h3Ckni1u2Au+Yiwxv0HbxkCgYEA/kVZSv9l/cH5053j
  FisqiRd9dRzqaau0tmJR8VOR3CzGsJaAAFTWSf6qVt7zZMnHQF7iRmV44KLfeN/f
  T+pTVtjZnuLM85ICx1TKBCMlsCHgue8B/JrK3CYiKP4y2q9iYp5wdySqBilF4XFV
  GDunBZSMI6b0AXyZRLDdhwCWJr0CgYEAwr0tjb6Cws20IZYYMyDVAJj1mf0TMGri
  g3L6dWrS4FofnCbXXkJrYKu403d7wdWQoFaxrGy1ZnJiDVZvZxd7UVqkbpD8LFtY
  DhVb6CMCQl6KeipF7S3eKhx/+tfaCXSHbwHlqdfnHD8D58bB/LFfG7yQ0lWBWXEq
  wyMfCFxRw8cCgYEAgtut2KsYEkCCEiZveDk+6s7sAhmfikKT/kkbYtdfebCRkM/j
  kEgZAHvPrmWPXY96u+YZDaGrU/B+kfalNruhqFBxrxOJ5tB+HZfFX9u2ya6luQsI
  OrhvLl1xtycbhPA98gMYXjjAR+t1y1BIOvB4RKbueGqzqRA20OM1HwVuQQECgYA7
  NLLl1lcBDPNIBs8itEeuH9MD1zp/TO/DETDug+TLCvtzSSfPY5gr0umleT0qCFkp
  NlJcXsyj8gC3l2DVUgFPEaTObMwOXFMgLQQ9Rm+IaB/n1nReEMTrvrB2PivvFfub
  F1OQ2LBOGSaB0B7oSbDlyOWq3Q4veEWNAF+N9itxvwKBgCyEuwtXLjTb6xOifeEY
  v53qh4DUS2QhILn8EOMAv/LWYDwYPxuF2kCYWfz3kxzITUJ1PAqbk46yW1Mb1bDe
  WTrrks13QseDtaCC5KsrkUEDod2mqjz82MOYVv9+dzHVsZwW/N4T4ld1Qu3A6Rwc
  Q5ammA+Nll3qZMtanGgSHS4J
type: kubernetes.io/tls

