apiVersion: apps/v1
kind: Deployment
metadata:
  name: customer-deployment
  labels:
    app: customer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: customer
  template:
    metadata:
      labels:
        app: customer
    spec:
      containers:
        - name: customer-container
          image: hm716/customer
          ports:
          - containerPort : 8080
          env:
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: username
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgres-secret
                key: password
          - name: POSTGRES_HOST_AUTH_METHOD
            valueFrom:
              configMapKeyRef:
                name: postgres-configmap
                key: database-url

---
apiVersion: v1
kind: Service
metadata:
  name: customer
spec:
  selector:
    app: customer
#  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
#      nodePort: 30000









