# DEPLOYMENT OF POSTGRES-DB
apiVersion: apps/v1
kind: Deployment                        # what kind of configuration
metadata:
  name: postgres-deployment                # 1) metadata name of the deployment
  labels:
    app: postgres
spec:                                   # 2) specification for deployment
  replicas: 1
  selector:
    matchLabels:                        # selector will connect all together with this key, value name
      app: postgres
  template:                             # template has its own metadata and spec section
    metadata:                           # and it all apply to a Pod
      labels:
        app: postgres                      # specify a label in form of key, value pair
    spec:                               # 2) specification or blueprint for pod (containers)
      containers:
      - name: postgres
        image: postgres                    # Docker hub image
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: password
        - name: POSTGRES_DB
          value: "postgres-banking"

#apiVersion: v1
#kind: Service                        # what kind of configuration
#metadata:
#  name: postgres-service
#spec:
#  selector:
#    app: postgres                    # this should be the same as label from deployment and pod
#  ports:
#    - protocol: TCP
#      port: 5432
#      targetPort: 5432              # this port should match with the port of deployment

---
# Service of POSTGRES-DB
apiVersion: v1
kind: Service                        # what kind of configuration
metadata:
  name: postgres
spec:
  selector:
    app: postgres                    # this should be the same as label from deployment and pod
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432              # this port should match with the port of deployment
      nodePort: 30500
